pool: 
  vmImage: ubuntu-latest

steps:
- task: DotNetCoreCLI@2
  inputs:
    azureSubscription: 'Abonnement Plateformes MSDN(2c2b7921-5234-44c3-a0ca-c72374e64a74)'
    command: 'build'
    arguments: '--configuration $(buildConfiguration)'